const { hashPassword } = require("../utils/password");

function seedDatabase() {
  return {
    users: [
      {
        id: 1,
        name: "Viresta Admin",
        email: "admin@viresta.com",
        password: hashPassword("Admin123!"),
        role: "admin",
        createdAt: "2024-03-01T00:00:00.000Z",
      },
      {
        id: 2,
        name: "Jordan Hale",
        email: "jordan@viresta.com",
        password: hashPassword("Agent123!"),
        role: "agent",
        phone: "+1 (555) 123-4567",
        image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=80",
        createdAt: "2024-03-01T00:00:00.000Z",
      },
    ],
    properties: [
      {
        id: 1,
        title: "Modern Villa with Pool",
        price: 850000,
        location: "Beverly Hills, CA",
        image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800&q=80",
        images: [
          "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1200&q=80",
          "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
          "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        ],
        type: "villa",
        status: "3D Tour Ready",
        beds: 5,
        baths: 4,
        sqft: 4200,
        yearBuilt: 2020,
        lotSize: "0.5 acres",
        parkingSpaces: 3,
        experiences: ["3D", "AR", "VR"],
        description:
          "Walk this villa room by room before you visit. Explore the open living spaces, outdoor kitchen, and pool terrace in an interactive 3D environment, then preview furniture placement with AR.",
        features: [
          "Swimming Pool",
          "Smart Home System",
          "Gourmet Kitchen",
          "Home Theater",
          "Wine Cellar",
          "Outdoor Kitchen",
          "Fire Pit",
          "Three-Car Garage",
        ],
        agentId: 2,
        createdAt: "2024-03-10T00:00:00.000Z",
      },
      {
        id: 2,
        title: "Luxury Downtown Apartment",
        price: 1200000,
        location: "Manhattan, NY",
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
        images: [
          "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80",
          "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
          "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80",
        ],
        type: "apartment",
        status: "VR Walkthrough",
        beds: 3,
        baths: 2,
        sqft: 2100,
        yearBuilt: 2019,
        lotSize: "Penthouse floor",
        parkingSpaces: 2,
        experiences: ["3D", "AR", "VR"],
        description:
          "A first-person walkthrough of a downtown penthouse. Move from the terrace to the living room, inspect finishes, and understand the layout without booking an on-site visit.",
        features: ["Doorman", "Private Terrace", "Floor-to-Ceiling Windows", "Gym Access", "Smart Lighting"],
        agentId: 2,
        createdAt: "2024-03-12T00:00:00.000Z",
      },
      {
        id: 3,
        title: "Waterfront Estate",
        price: 2100000,
        location: "Miami Beach, FL",
        image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
        images: [
          "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&q=80",
          "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80",
          "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdbc?w=800&q=80",
        ],
        type: "house",
        status: "AR Preview",
        beds: 6,
        baths: 5,
        sqft: 6100,
        yearBuilt: 2021,
        lotSize: "1.2 acres",
        parkingSpaces: 4,
        experiences: ["3D", "AR", "VR"],
        description:
          "Experience the scale of this waterfront estate remotely. Use the 3D model to move between wings, then place the home in your surroundings with AR to understand true size and orientation.",
        features: ["Waterfront", "Private Dock", "Wine Cellar", "Guest House", "Infinity Pool"],
        agentId: 2,
        createdAt: "2024-03-15T00:00:00.000Z",
      },
    ],
    posts: [
      {
        id: 1,
        title: "Why 3D Walkthroughs Change How Buyers Choose Homes",
        slug: "3d-walkthroughs-change-home-buying",
        excerpt: "Interactive 3D tours help buyers understand space, light, and flow before they ever set foot on the property.",
        image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&q=80",
        category: "3d",
        author: "Sarah Johnson",
        date: "2024-03-15",
        readTime: "5 min read",
        tags: ["3D", "Virtual Tours", "Buyers"],
        content:
          '<p class="mb-4">Photographs and floor plans still matter, but they cannot show how a home actually feels. A 3D walkthrough lets buyers move through rooms, check sight lines, and compare layouts from anywhere.</p><h2 class="text-2xl font-semibold mt-8 mb-4">What buyers notice first</h2><ul class="list-disc pl-6 mb-4"><li class="mb-2">How rooms connect</li><li class="mb-2">Natural light throughout the day</li><li class="mb-2">True scale of kitchens, bedrooms, and outdoor areas</li></ul><h2 class="text-2xl font-semibold mt-8 mb-4">Why agents use it</h2><p class="mb-4">Remote buyers can shortlist properties faster. Agents spend less time on mismatched showings and more time with people who already understand the space.</p>',
      },
      {
        id: 2,
        title: "AR Property Previews: Placing Architecture in the Real World",
        slug: "ar-property-previews",
        excerpt: "Augmented reality lets clients preview scale, interiors, and unbuilt developments against their actual surroundings.",
        image: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80",
        category: "ar-vr",
        author: "Michael Chen",
        date: "2024-03-12",
        readTime: "7 min read",
        tags: ["AR", "Architecture", "Mobile"],
        content:
          '<p class="mb-4">AR is most useful when a property is not finished yet, or when a buyer needs to understand size. Clients can place a model on a table, walk around it, and compare it with nearby buildings.</p><h2 class="text-2xl font-semibold mt-8 mb-4">Common uses</h2><ul class="list-disc pl-6 mb-4"><li class="mb-2">Furniture and interior placement</li><li class="mb-2">Development previews for off-plan homes</li><li class="mb-2">Scale-aware visualization on site</li></ul>',
      },
      {
        id: 3,
        title: "Designing Floor Plans That Connect to 3D Environments",
        slug: "interactive-floor-plans-3d",
        excerpt: "Clickable rooms and measured plans become far clearer when they open directly into a 3D scene.",
        image: "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&q=80",
        category: "property",
        author: "David Rodriguez",
        date: "2024-03-10",
        readTime: "6 min read",
        tags: ["Floor Plans", "3D", "UX"],
        content:
          '<p class="mb-4">A static PDF plan still leaves people guessing. Interactive plans let users tap a room and drop into that space, with measurements that stay consistent between 2D and 3D.</p><p class="mb-4">Viresta treats the floor plan as a map of the same digital property, not a separate document.</p>',
      },
    ],
    inquiries: [],
    tours: [],
  };
}

module.exports = { seedDatabase };
